//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_PostTypeMaster
    {
        public OWL_PostTypeMaster()
        {
            this.OWL_PostsMaster = new HashSet<OWL_PostsMaster>();
        }
    
        public int PostTypeId { get; set; }
        public string PostType { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual ICollection<OWL_PostsMaster> OWL_PostsMaster { get; set; }
    }
}
