//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_DocumentMaster
    {
        public int DocNo { get; set; }
        public string DocTitle { get; set; }
        public string DocName { get; set; }
        public string DocUploadedBy { get; set; }
        public Nullable<int> DocCategoryName { get; set; }
        public Nullable<System.DateTime> DocRelatedYear { get; set; }
        public Nullable<System.DateTime> DocUploadedOn { get; set; }
        public Nullable<System.DateTime> DocUpdatedOn { get; set; }
        public string Description { get; set; }
        public string FolderName { get; set; }
        public string DocFileType { get; set; }
        public Nullable<double> DocFileSizeIn_KB { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string Remark { get; set; }
    
        public virtual OWL_DocCategoryMaster OWL_DocCategoryMaster { get; set; }
        public virtual OWL_EmployeeMaster OWL_EmployeeMaster { get; set; }
    }
}
