//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_BusinessServicesMaster
    {
        public int ServiceNo { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ServiceCategory { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual OWL_ServicesCategoryMaster OWL_ServicesCategoryMaster { get; set; }
    }
}
