//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_JobTypeMaster
    {
        public OWL_JobTypeMaster()
        {
            this.OWL_JobsPostMaster = new HashSet<OWL_JobsPostMaster>();
        }
    
        public int JobTypeId { get; set; }
        public string JobType { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual ICollection<OWL_JobsPostMaster> OWL_JobsPostMaster { get; set; }
    }
}
