//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_PostsMaster
    {
        public OWL_PostsMaster()
        {
            this.OWL_PostsMaster1 = new HashSet<OWL_PostsMaster>();
        }
    
        public int Id { get; set; }
        public string PostAuthor { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostContent { get; set; }
        public string FeaturedImg { get; set; }
        public string ThumbImg { get; set; }
        public string FileFolderName { get; set; }
        public string PostTitle { get; set; }
        public string PostExcerpt { get; set; }
        public string BulletPoint { get; set; }
        public Nullable<int> PostStatus { get; set; }
        public Nullable<int> CommentStatus { get; set; }
        public string PostPassword { get; set; }
        public string PostName { get; set; }
        public string ToPingTags { get; set; }
        public string Pinged { get; set; }
        public Nullable<System.DateTime> PostUpdatedOn { get; set; }
        public string PostContentFiltered { get; set; }
        public Nullable<int> PostParent { get; set; }
        public string Guid { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<int> PostType { get; set; }
        public string PostMimeType { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual OWL_EmployeeMaster OWL_EmployeeMaster { get; set; }
        public virtual ICollection<OWL_PostsMaster> OWL_PostsMaster1 { get; set; }
        public virtual OWL_PostsMaster OWL_PostsMaster2 { get; set; }
        public virtual OWL_PostTypeMaster OWL_PostTypeMaster { get; set; }
        public virtual OWL_StatusListMaster OWL_StatusListMaster { get; set; }
        public virtual OWL_StatusListMaster OWL_StatusListMaster1 { get; set; }
    }
}
