//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_CityMaster
    {
        public OWL_CityMaster()
        {
            this.OWL_CareersMaster = new HashSet<OWL_CareersMaster>();
            this.OWL_CareersMaster1 = new HashSet<OWL_CareersMaster>();
            this.OWL_EmployeeMaster = new HashSet<OWL_EmployeeMaster>();
            this.OWL_JobsPostMaster = new HashSet<OWL_JobsPostMaster>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public int RelatedStateId { get; set; }
    
        public virtual ICollection<OWL_CareersMaster> OWL_CareersMaster { get; set; }
        public virtual ICollection<OWL_CareersMaster> OWL_CareersMaster1 { get; set; }
        public virtual OWL_StateMaster OWL_StateMaster { get; set; }
        public virtual ICollection<OWL_EmployeeMaster> OWL_EmployeeMaster { get; set; }
        public virtual ICollection<OWL_JobsPostMaster> OWL_JobsPostMaster { get; set; }
    }
}
