//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_SectorTypeMaster
    {
        public OWL_SectorTypeMaster()
        {
            this.OWL_BusinessPlanMaster = new HashSet<OWL_BusinessPlanMaster>();
            this.OWL_ClientMaster = new HashSet<OWL_ClientMaster>();
            this.OWL_QuestionMaster = new HashSet<OWL_QuestionMaster>();
            this.OWL_TagsMaster = new HashSet<OWL_TagsMaster>();
        }
    
        public int SectorTypeId { get; set; }
        public string SectorType { get; set; }
    
        public virtual ICollection<OWL_BusinessPlanMaster> OWL_BusinessPlanMaster { get; set; }
        public virtual ICollection<OWL_ClientMaster> OWL_ClientMaster { get; set; }
        public virtual ICollection<OWL_QuestionMaster> OWL_QuestionMaster { get; set; }
        public virtual ICollection<OWL_TagsMaster> OWL_TagsMaster { get; set; }
    }
}
