//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_DocTypeMaster
    {
        public OWL_DocTypeMaster()
        {
            this.OWL_DocCategoryMaster = new HashSet<OWL_DocCategoryMaster>();
        }
    
        public int DocTypeNo { get; set; }
        public string DocType { get; set; }
    
        public virtual ICollection<OWL_DocCategoryMaster> OWL_DocCategoryMaster { get; set; }
    }
}
