//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_JobsPostMaster
    {
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> Qualification { get; set; }
        public string KeySkills { get; set; }
        public Nullable<int> Exp_InYears { get; set; }
        public Nullable<int> Available_NoOfPost { get; set; }
        public Nullable<int> JobType { get; set; }
        public Nullable<int> JobMode { get; set; }
        public Nullable<int> JobLocation { get; set; }
        public string PublishedBy { get; set; }
        public Nullable<System.DateTime> PublishedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual OWL_CityMaster OWL_CityMaster { get; set; }
        public virtual OWL_EmployeeMaster OWL_EmployeeMaster { get; set; }
        public virtual OWL_JobModeMaster OWL_JobModeMaster { get; set; }
        public virtual OWL_JobTypeMaster OWL_JobTypeMaster { get; set; }
        public virtual OWL_QualificationMaster OWL_QualificationMaster { get; set; }
        public virtual OWL_StatusListMaster OWL_StatusListMaster { get; set; }
    }
}
