//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_QuestionMaster
    {
        public int QuestionNo { get; set; }
        public Nullable<int> SectorType { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> CreationDT { get; set; }
        public Nullable<System.DateTime> UpdationDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual OWL_EmployeeMaster OWL_EmployeeMaster { get; set; }
        public virtual OWL_SectorTypeMaster OWL_SectorTypeMaster { get; set; }
    }
}
