//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_CareersMaster
    {
        public int ApplicationNo { get; set; }
        public string ApplicaintName { get; set; }
        public string Gender { get; set; }
        public string ApplicaintEmail { get; set; }
        public string ApplicaintMobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ApplicaintAddress { get; set; }
        public Nullable<int> ApplicaintLocation { get; set; }
        public Nullable<int> ApplicaintPreferedLocation { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<int> DesignationName { get; set; }
        public Nullable<int> DepartmentName { get; set; }
        public string AttachmentFolderName { get; set; }
        public string AttachedResume { get; set; }
        public string AttachmentExtension { get; set; }
        public string BusinessName { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remark { get; set; }
    
        public virtual OWL_CityMaster OWL_CityMaster { get; set; }
        public virtual OWL_CityMaster OWL_CityMaster1 { get; set; }
        public virtual OWL_DepartmentMaster OWL_DepartmentMaster { get; set; }
        public virtual OWL_DesignationMaster OWL_DesignationMaster { get; set; }
        public virtual OWL_QualificationMaster OWL_QualificationMaster { get; set; }
        public virtual OWL_StatusListMaster OWL_StatusListMaster { get; set; }
    }
}
