//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_EmployeeDetail
    {
        public string EmpEmail { get; set; }
        public string ProfilePic { get; set; }
        public string About { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> JobDesignation { get; set; }
        public Nullable<int> Country { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string TwitterProfileUrl { get; set; }
        public string FacebookProfileUrl { get; set; }
        public string InstagramProfileUrl { get; set; }
        public string LinkedinProfileUrl { get; set; }
        public string LinkType { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual OWL_EmployeeMaster OWL_EmployeeMaster { get; set; }
    }
}
