//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_UserMaster
    {
        public OWL_UserMaster()
        {
            this.OWL_EmployeeMaster = new HashSet<OWL_EmployeeMaster>();
        }
    
        public int UserTypeId { get; set; }
        public string UserTypeName { get; set; }
    
        public virtual ICollection<OWL_EmployeeMaster> OWL_EmployeeMaster { get; set; }
    }
}
