//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_ClientMaster
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> BelongResource { get; set; }
        public Nullable<int> SectorType { get; set; }
        public string AuthorizedPerson { get; set; }
        public Nullable<int> Designation { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> RelatedState { get; set; }
        public Nullable<int> RelatedCity { get; set; }
        public string Url { get; set; }
        public Nullable<int> BusinessPlan { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual OWL_BusinessPlanMaster OWL_BusinessPlanMaster { get; set; }
        public virtual OWL_StatusListMaster OWL_StatusListMaster { get; set; }
        public virtual OWL_ClientMaster OWL_ClientMaster1 { get; set; }
        public virtual OWL_ClientMaster OWL_ClientMaster2 { get; set; }
        public virtual OWL_DesignationMaster OWL_DesignationMaster { get; set; }
        public virtual OWL_ResourceMaster OWL_ResourceMaster { get; set; }
        public virtual OWL_SectorTypeMaster OWL_SectorTypeMaster { get; set; }
        public virtual OWL_StateMaster OWL_StateMaster { get; set; }
    }
}
