//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_ServicesCategoryMaster
    {
        public OWL_ServicesCategoryMaster()
        {
            this.OWL_BusinessServicesMaster = new HashSet<OWL_BusinessServicesMaster>();
        }
    
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual ICollection<OWL_BusinessServicesMaster> OWL_BusinessServicesMaster { get; set; }
    }
}
