//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_StateMaster
    {
        public OWL_StateMaster()
        {
            this.OWL_CityMaster = new HashSet<OWL_CityMaster>();
            this.OWL_ClientMaster = new HashSet<OWL_ClientMaster>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public int RelatedCountryId { get; set; }
    
        public virtual ICollection<OWL_CityMaster> OWL_CityMaster { get; set; }
        public virtual ICollection<OWL_ClientMaster> OWL_ClientMaster { get; set; }
        public virtual OWL_CountryMaster OWL_CountryMaster { get; set; }
    }
}
