//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEXE_OWL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWL_DesignationMaster
    {
        public OWL_DesignationMaster()
        {
            this.OWL_CareersMaster = new HashSet<OWL_CareersMaster>();
            this.OWL_ClientMaster = new HashSet<OWL_ClientMaster>();
        }
    
        public int DesignationId { get; set; }
        public string DesignationName { get; set; }
    
        public virtual ICollection<OWL_CareersMaster> OWL_CareersMaster { get; set; }
        public virtual ICollection<OWL_ClientMaster> OWL_ClientMaster { get; set; }
    }
}
